version: 0.2
phases: 
  install:
    runtime-versions:
        docker: 18     
    commands: 
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2&
      - timeout 15 sh -c "until [ "`/usr/bin/docker inspect -f {{.State.Running}} CONTAINERNAME`"=="true" ]; do sleep 0.1; done;"

     
  pre_build: 
    commands: 
    - echo Logging in to Amazon ECR.... 
    - aws --version
    # update the following line with your own region
    - $(aws ecr get-login --no-include-email --region eu-west-1)
    - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
    - IMAGE_TAG=${COMMIT_HASH:latest}
    - REPOSITORY_URI=865915813093.dkr.ecr.ca-central-1.amazonaws.com/ecr 
  build: 
    commands: 
    - echo Build started on `date` 
    - echo Building the Docker image... 
    # update the following line with the name of your own ECR repository
    - docker build -t $REPOSITORY_URI:latest .
    # update the following line with the URI of your own ECR repository (view the Push Commands in the console)
    - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG 
  post_build: 
    commands: 
    - echo Build completed on `date` 
    - echo pushing to repo
    # update the following line with the URI of your own ECR repository
    - docker push $REPOSITORY_URI:latest
    - docker push $REPOSITORY_URI:$IMAGE_TAG
    - echo Writing image definitions file... 
    #- printf '[{"ImageURI":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imageDetail.json
    - printf '{"ImageURI":"%s"}' $REPOSITORY_URI:$IMAGE_TAG > imageDetail.json
artifacts:
  files:
    - imageDetail.json



# version: 0.2

# phases: 
#     install:
#         runtime-versions:
#             nodejs: 10
#             docker: 18
#         commands:
#             - echo "installing something"
#             # - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2&
#             # - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
#     pre_build:
#         commands: 
#             - aws --version
#             - echo "we are in the pre build phase"
#             # - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
#             - $(aws ecr get-login --no-include-email --region ca-central-1)
#             - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
#             - IMAGE_TAG=${COMMIT_HASH:=latest}
#             - REPOSITORY_URI=865915813093.dkr.ecr.ca-central-1.amazonaws.com/ecr
#     build:
#         commands:
#             - echo Build started on `date`
#             # - echo "we are in the build block"
#             # - echo "we will run some tests"
#             # - grep -Fq "Congratulations" index.html
#             - echo Building the Docker image...          
#             # - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
#             - docker build -t $REPOSITORY_URI:latest .
#             # - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
#             - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
#     post_build:
#         commands:
#             - echo "we are in the post build phase"
#             - echo Pushing the Docker image...
#             # - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
#             - docker push $REPOSITORY_URI:latest
#             # - docker push $REPOSITORY_URI:$IMAGE_TAG